### ISSUE TITLE
how do i list my `doing later` stuff?

### ISSUE THREAD

**Issue by pvinis** [ttscoff/doing#102]
i'd like to list them and then somehow pick one to `doing now`.

is that possible somehow?

**Comment by pvinis** [comment]
so i actually found `doing show later`, but now i don't know how to move this to `doing now`

**Comment by ttscoff** [comment]
Doing doesn't handle that kind of manipulation, it's best to just open the"what was I doing" file in a text editor (or taskpaper).

- Brett

**Comment by pvinis** [comment]
ah alright. thank you :D
