### ISSUE TITLE
doing meanwhile produces error

### ISSUE THREAD

**Issue by claman** [ttscoff/doing#103]
When I try to create a new meanwhile entry, the command returns `error: undefined method 'gsub' for []:Array`

I can just make a normal entry via `now`, then open it in an editor and manually tag it with `@meanwhile`, in which case `doing meanwhile` works to mark that entry as done.

**Comment by ttscoff** [comment]
I can replicate this, will look into it as I have time. Pull requests 
welcome.

-Brett

**Comment by ttscoff** [comment]
Found this one and fixed in 1.0.13.

**Comment by claman** [comment]
Can confirm that this fixes the issue. Many thanks!
