### ISSUE TITLE
Error on first install, (mac OS Mojave)

### ISSUE THREAD

**Issue by andrewsleigh** [ttscoff/doing#104]
Sorry, probably total newbie error, but I tried installing this, by running `[sudo] gem install doing`, but any command results in this error message (which means nothing to me...) e.g. 

`
> doing config
Traceback (most recent call last):
	3: from /usr/local/bin/doing:23:in `<main>'
	2: from /usr/local/bin/doing:23:in `load'
	1: from /usr/local/lib/ruby/gems/2.5.0/gems/doing-1.0.26/bin/doing:29:in `<top (required)>'
/usr/local/lib/ruby/gems/2.5.0/gems/doing-1.0.26/lib/doing/wwid.rb:72:in `configure': undefined method `[]' for nil:NilClass (NoMethodError)
`

`ruby -v` returns:
`ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]`

`GLI_DEBUG=true doing` returns the same error message

**Comment by ttscoff** [comment]
Try running `gem install doing` again to get the latest version 1.0.27. 
I think I've fixed this error having to do with the initial config file 
not existing yet.

-Brett

**Comment by andrewsleigh** [comment]
Yep, that worked - thank you!
