### ISSUE TITLE
Error on every command

### ISSUE THREAD

**Issue by johnnypea** [ttscoff/doing#105]
`/usr/local/lib/ruby/gems/2.7.0/gems/doing-1.0.29/lib/doing/wwid.rb:602: warning: deprecated Object#=~ is called on Array; it always returns nil
`

Thanks for the tool ;).

**Comment by ttscoff** [comment]
Interesting, not sure why this hasn't come up before. I'll put an update 
out soon with a fix for this.

Thanks,
Brett

**Comment by ttscoff** [comment]
Pushed v1.0.30 which should fix this. Let me know if you still have 
issues.

-Brett

**Comment by johnnypea** [comment]
Everything is fine now. Thank you for a quick fix.
