### ISSUE TITLE
Cannot add tags with values

### ISSUE THREAD

**Issue by NeelsK** [ttscoff/doing#108]
When entering a tag with a value the following error occurs:

abcs-iMac:~ abc$ doing now New task @sampletag(**sample value**)
-bash: syntax error near unexpected token `('

I use tags with values a lot to enable logging of support ticket numbers ie @ticket(**12345**) which streamlines my month-end reporting a lot.

Regards,
Neels

**Comment by ttscoff** [comment]
That's bash giving you the error, not doing. Use quotes around your task 
and tags.

	doing now "New task @sampletag(sample value)"


-Brett

**Comment by NeelsK** [comment]
You're a legend!! Thanks
