### ISSUE TITLE
--help flag is near useless

### ISSUE THREAD

**Issue by lolbinarycat** [ttscoff/doing#109]
The help flag doesn't really tell you how thing work. There are a number of issues:
1. No distinction between literal input and a description of accepted input.
For example the `done` subcommand: `doing [global options] done [command options] entry`
Here `entry` (a description of what that argument is) and `done` (the literal string "done") are given no differentiation.
2. No explanations for arguments
While flags have a nice synopsis, the same cannot be said for other arguments.
Take my previous example, what does `entry` mean?
Is it:
- the exact body of an entry to mark
- a numerical offset
- the name of a section
- the name of a tag
- the exact date of an entry
- the literal word "entry"
Who knows?

There's more, but I don't really feel like listing everything right now, so I'm just going to leave it there.

**Comment by ttscoff** [comment]
I think you’re thinking of documentation.

- Brett

**Comment by lolbinarycat** [comment]
> I think you’re thinking of documentation. - Brett

I don't think I am. And if there is documentation, it should be linked to by `help` (`ls` does this).  Having documentation does not excuse having `help`'s output be sloppy and unclear.

**Comment by ttscoff** [comment]
I welcome anyone else’s input, but I disagree with most of your premise. If you read the documentation, the prompts provided by the help system make perfect sense. Linking the documentation is feasible, but how did you find this project if not through either the project page on my site or via here (GitHub) where the readme is quite detailed?

This is a personal project I give away for free. I don’t owe you anything, and your insulting and entitled tone is not going to prompt any changes.

- Brett

**Comment by vcavallo** [comment]
> if there is documentation

I've found the `doing` [README](https://github.com/ttscoff/doing/blob/master/README.md) to be quite extensive. Maybe I've spent most of my time around a set of outlier repos, but having the full documentation live on the readme and keeping the `--help` to a quick reminder of the flags is entirely standard in my view.

Respectfully, if you think the readme should also be reflected in ruby docs or something, you could volunteer your time to submit a pull request, @lolbinarycat, just like Brett has volunteered his time to build this whole project.

**Comment by lolbinarycat** [comment]
I may submit a PR, although I might be more inclined to do so if I knew anything about ruby, but I'll give it a shot.

**Comment by lolbinarycat** [comment]
can anyone point me to the file that contains the help function?

**Comment by ttscoff** [comment]
The help is generated from the desc tags in the main doing file. Each command has its own, and the main banner is defined in bin/doing.

- Brett

**Comment by lolbinarycat** [comment]
what defines the desc tags? I want to add text to the bottom of the `help` output, but that doesn't seem to be possible.

**Comment by ttscoff** [comment]
It is not.

- Brett

**Comment by ttscoff** [comment]
You have to consider that in the years doing has existed, no one has ever had the issue with the help system that you have.

But if you really feel the world needs this change, see the documentation for GLI.

- Brett

**Comment by lolbinarycat** [comment]
> You have to consider that in the years doing has existed, no one has ever had the issue with the help system that you have.

Noone has mentioned having the issue, you mean. I would imagine most people would just not use it if they didn't understand.  It's what I already did, last time I installed this.

**Comment by ttscoff** [comment]
Which is fine. I lose zero dollars when someone can't take the time to read the docs and abandons the project.

I'm really not normally this much of a dick. It's just an old project that I've put a lot of time into but which currently has zero of my attention. My personal life has me crabby right now, so I'm not treating this with the concern I would one of my commercial projects. I'm just not up to dealing with it. Sorry off I come off as aloof or harsh.

- Brett

**Comment by ttscoff** [comment]
Ok, again, I apologize for my crankiness. I appreciate you trying to help. The main description is found in bin/doing on a line starting with 'program_desc'. You can also add a longer description that will appear beneath that short description using `program_long_desc '[long description, including line breaks and urls]` as documented [in the GLI rdocs](https://davetron5000.github.io/gli/rdoc/index.html). If you just want to add a link to the project page or GitHub readme, you can let me know what you're thinking and I'd be happy to just insert it for you.

**Comment by lolbinarycat** [comment]
At this point, I think just redirecting people to the `README` file is the best course of action.

**Comment by ttscoff** [comment]
Just to put a bow on this, variables are now all-caps in the help, e.g. `doing [global options] now [command options] ENTRY`, which should be a standard enough convention to avoid confusion. I've also added an EXAMPLES section to the help for all commands.
