### ISSUE TITLE
Error installing on Mac High Sierra - can't dup NilClass

### ISSUE THREAD

**Issue by nissae** [ttscoff/doing#111]
I've tried to install this on two laptops and get the same error both times. 

Mac 10.13.6

ruby -v: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]

GLI_DEBUG=true doing (or anything else I try):
/Library/Ruby/Gems/2.3.0/gems/doing-1.0.34/lib/doing/wwid.rb:132:in `dup': can't dup NilClass (TypeError)
	from /Library/Ruby/Gems/2.3.0/gems/doing-1.0.34/lib/doing/wwid.rb:132:in `configure'
	from /Library/Ruby/Gems/2.3.0/gems/doing-1.0.34/bin/doing:30:in `<top (required)>'
	from /usr/local/bin/doing:22:in `load'
	from /usr/local/bin/doing:22:in `<main>'

Any help would be appreciated. I would love to use this!

**Comment by ttscoff** [comment]
That error is occurring while reading your config file. It should be 
writing a base config file if one doesn't exist. Do you have a valid 
YAML `.doingrc` file in your home directory?

-Brett

**Comment by nissae** [comment]
Thank you for the quick response!

I checked my home directory (I am assuming you mean my username directory ~/), and no, I do not have that file. I also did a search, just in case, and did not find it.

**Comment by ttscoff** [comment]
If it's not creating a config automatically for you, you'll probably 
need to create it yourself: 
https://github.com/ttscoff/doing/#configuration

If it's having trouble writing to the file, though, you'll probably 
continue to run into problems until that's figured out...

-Brett

**Comment by nissae** [comment]
I created the config file myself. When I tried running "doing config" I had to go into my Security & Privacy Preferences and allow it. It seems to be working now. Fingers crossed. Thank you!
