### ISSUE TITLE
Pick entry from later

### ISSUE THREAD

**Issue by delucca** [ttscoff/doing#112]
Hi!

I'm using `doing` for a while, and I'm loving the tool :)

I would like to pick a given entry I've added to the `Later` section (or a custom section) and move it to the `Currently` section. How do I do it?

**Comment by ttscoff** [comment]
You can use the archive commands to move the last X items from one 
section to another, but you can't cherry pick them. The easiest way to 
do that is to open the doing file in a text editor (or in TaskPaper) and 
manage them directly.

-Brett

**Comment by delucca** [comment]
Ah ok, nice!

A cherry-pick option would be great :)

**Comment by delucca** [comment]
@ttscoff quick question, can I set the order to archive the most recent entries? (instead of the oldest)

**Comment by ttscoff** [comment]
No. It's basically just taking X number of lines from the top of a 
section, not parsing them by date or anything.

-Brett

**Comment by delucca** [comment]
@ttscoff I was trying this command, and actually the `-k` argument decide how many to **keep** not how many to **pass**

**Comment by sghosh1111** [comment]
> Ah ok, nice!
> 
> A cherry-pick option would be great :)

I would second that.

A second problem is that "doing archive" is not doing anything.

I initially tried running "doing archive -t Later" to move my current job to the "Later" section but the command did not run successfully. It gave no error message but it did not also move my current job to the "Later" section.

I then tried running "doing archive" to move my current job to the "Archive" section but I again got the same result as before.

What more information can I provide which would help in figuring out what is going on?

**Comment by ttscoff** [comment]
Resolving this as the new `doing select` in 2.0 covers this, and most commands now have `--search` and `--tag` filters to target older entries based on content or tags. Many commands now have an `--interactive` flag that offers a menu for cherry picking as well.
