### ISSUE TITLE
Not using ~/.doingrc for settings or doing_file location

### ISSUE THREAD

**Issue by dskesler** [ttscoff/doing#120]
Doing command works except that it does not seem to use the .doingrc file located in ~/.doingrc.
When I issue command `doing config`, it does open the correct .doingrc file in the correct editor.
However, the doing_file name and path are not correct. The text gets sent to the default file "what_i_was_doing.md" instead of the one specified in the .doingrc file. I am also missing all the views and templates configured in my .doingrc.

When I issue `doing --config_file="Users/me/.doingrc"` I receive: `error: No such file or directory @ rb_sysopen - Users/me/.doingrc`

The `which doing` command shows: `/Users/me/.rbenv/shims/doing`. That seems odd, so thought I'd mention it in case it helps troubleshoot.

Thanks for any suggestions.

**Comment by ttscoff** [comment]
Well, first, the `--config_file` should be "/Users/me/.doingrc", it's 
missing the leading slash. That said, is it possible there's an error in 
the file that might make doing choke when reading it? I'd be happy to 
take a look at it if you want to share it.

-Brett

**Comment by dskesler** [comment]
Yes, you were correct. The problem must have been an incorrect syntax or formatting in the .doingrc file. Once I copied the basic configuration .doingrc from your blog post about doing, it is using the settings from the file correctly. 

Thank you very much for the help.
