### ISSUE TITLE
run_after doesn*t work 

### ISSUE THREAD

**Issue by can-I-do** [ttscoff/doing#123]
hey,

first thx for the tool and the nice guide putting it into the status bar from iterm!
I just followed the guide and the "run_after" command doesnt seem to do anything for me :(

i just added a new line at the bottom:
run_after: /path/smth.sh 
also tried 
run_after: "/path/smth.sh"

any advice here?

**Comment by can-I-do** [comment]
doing -v
doing version 1.0.93

**Comment by can-I-do** [comment]
I also tried it with hooks, as I found it in the docs ;) but still doesn't seem to work. Maybe smth is wrong with my system...

**Comment by ttscoff** [comment]
Hooks won't do anything unless you install 2.0pre from source, which I wouldn't recommend yet. It's a new feature under development.

But I think when they are released, they might solve the issue. They're more reliable than run_after, overall. You might have to wait a bit, though.

- Brett

**Comment by can-I-do** [comment]
so, I installed 2.0, first of all thx for the update!
It still is not working... 
`plugins:
  plugin_path: "/Users/can-I-do/.config/doing/plugins"`

`cat /Users/can-I-do/.config/doing/plugins/post_write.rb
Doing::Hooks.register :post_write do |filename|
  res = `/bin/bash ~/after_doing.sh`.strip
  Doing.logger.debug('Hooks:', res)
end` 

if I manually run /bin/bash ~/after_doing.sh it is working, but from doing now  or finish it is not

**Comment by ttscoff** [comment]
Does the debug log show up when you run a command? (be sure to run with `doing --debug`, or change it to `Doing.logger.warn` for testing purposes)

**Comment by ttscoff** [comment]
Also try running `DOING_PLUGIN_DEBUG=true doing` to see if the hook is registering correctly. You should see:

```
>  Hook Manager: Registered post_write hook
```

**Comment by can-I-do** [comment]
```
❯ doing now test hook
    New entry: added "Test hook" to Currently
❯ DOING_PLUGIN_DEBUG=true doing
>  Logging at level: debug
       8:47am: Test hook (Currently)
>  Plugin Manager: Registered export plugin "csv"
>  Plugin Manager: Registered export plugin "html"
>  Plugin Manager: Registered export plugin "timeline"
>  Plugin Manager: Registered export plugin "markdown"
>  Plugin Manager: Registered export plugin "taskpaper"
>  Plugin Manager: Registered export plugin "template"
>  Plugin Manager: Registered export plugin "doing"
>  Plugin Manager: Registered import plugin "calendar"
>  Plugin Manager: Registered import plugin "doing"
>  Plugin Manager: Registered import plugin "timing"
>  Hook Manager: Registered post_write hook
>      Config: Local config files found:
>         ENV: No EDITOR environment variable, testing available editors
```
This seems to work. Same with `Doing.logger.warn` 
```❯ doing now test hook
    New entry: added "Test hook" to Currently
>       Hooks: /bin/bash ~/after_doing.sh```

but still it is not doing smth :/  I am really not sure why ... probably some really silly mistake on my side than.

**Comment by can-I-do** [comment]
![CleanShot 2021-11-23 at 09 02 54](https://user-images.githubusercontent.com/60129163/142988654-4308c071-5941-42a1-9c01-4584efcd4a2d.gif)

**Comment by ttscoff** [comment]
- I doubt it will help, but just to be sure could you try with an 
absolute path instead of the `~` in the hook?

- Also, have you tested with any other scripts to see if there's 
something specific about after_doing.sh that might be causing issues?

- And does after_doing.sh have executable (`chmod a+x`) permissions? (I 
know running via /bin/bash shouldn't require it, but it could be a 
general permissions issue).

**Comment by can-I-do** [comment]
- no doesn't work

- tried it with an echo "test" script -> didn't work

- yes after and test.sh are executable 

really strange :/ and sad, but I guess it is something on my side if it works for others. dont want to bother you further with my problems :D

**Comment by ttscoff** [comment]
Echoing to STDOUT may or may not show up at all, given it's running 
inside a process, but the Doing.logger statements definitely should.

I don't mind debugging this with you, I'd like this feature to work for 
everyone, but I'm not sure what else to try right now. If I think of 
anything else, I will let you know. And if you come up with any more 
clues, please let me know!

-Brett

**Comment by can-I-do** [comment]
thanks for your help! I will try my best to figure it out
