### ISSUE TITLE
[BUG] Monterey 12.1 error: No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by alwillis** [ttscoff/doing#131]
**Describe the bug**

After installing Doing on Monterey 12.1, I get
`error: No such file or directory @ rb_sysopen /Users/awillis/.local/share/doing/what_was_i_doing.md.`

**Desktop (please complete the following information):**

 - Platform: Mac
 - OS: Monterrey
 - Version 12.1

**Doing version**

 - 2.1.10

**Ruby version**

 - ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin21]

**Additional context**

I'm using [rbenv](https://github.com/rbenv/rbenv) 1.2.0 to manage my Ruby installations.

**Comment by ttscoff** [comment]
It should have generated the file if it didn't exist, but run this and 
see if it fixes it:


```
mdkir -p ~/.local/share/doing
touch ~/.local/share/doing/what_was_i_doing.md
```

**Comment by alwillis** [comment]
That worked; thanks.
