### ISSUE TITLE
Sorting of entries in doing_file

### ISSUE THREAD

**Issue by daftmilk** [ttscoff/doing#132]
**Is your feature request related to a problem? Please describe.**
I am doing a lot of hand-editing in the doing_file and it would very helpful if the latest entries would be on top like I was used to with doing v1.

I'd like to configure doing to put the latest entries on top (sort descending).

**Describe the solution you'd like**
As in views configure this option to sort descending in the doing_file itself.

**Comment by ttscoff** [comment]
Consider it done. When I looked at it, it turned out that after the big 
2.0 refactor I never had it sorting the doing file output at all. You 
wouldn't notice unless you edited manually as everything is sorted in 
memory after reading the file, but it was just writing out the array of 
items as is. I changed it to sort descending by default (newest at top), 
but also added a config setting to change it:

	doing_file_sort: asc

Since it doesn't make any difference what order the entries are in, only 
the sections, this is just a matter of convenience for users who do edit 
regularly.

This will be available in v2.1.20, which I'll release after testing.

-Brett

**Comment by daftmilk** [comment]
Hey Brett,

you are awesome.

I've been using doing, nvalt and marked (one time buyer, then via setapp) for more than 10 years now.
I can't wait to try nvultra.

I decided it's overdue to support you financially with $ 3 a month. I hope the small contribution helps.

A small (annoying) thing:
I noticed on your newletter-subscription form, that it is not linked to a https-encrypted site:
http://sendy…

Regards,
Daniel

----------------8<---------sNip!-------------

Daniel Müller
Adresse:	Kaulbachstraße 9 E, 12247 Berlin
Telefon: 	0049 176 12 22 22 60

**Comment by ttscoff** [comment]
Oops, mistake in the refactoring I was doing. Pushing a new gem now. Let me know if v2.1.22 fixes it for you.

-Brett

**Comment by daftmilk** [comment]
Dear Brett,

this fixed it. Thanks a lot!

Regards,
Daniel

> Am 21.01.2022 um 22:34 schrieb Brett Terpstra ***@***.***>:
> 
> 
> Oops, mistake in the refactoring I was doing. Pushing a new gem now. Let me know if v2.1.22 fixes it for you.
> 
> -Brett
> 
> 
> 
> On 21 Jan 2022, at 11:49, Daft Milk wrote:
> 
> > Hello Brett,
> >
> > it is sorting like i wanted it! Thanks a lot!
> > However I get some warnings:
> >
> > ```
> > /opt/homebrew/Cellar/gem-doing/2.1.21/gems/doing-2.1.21/bin/doing:29: warning: already initialized constant InvalidExportType
> > /opt/homebrew/Cellar/gem-doing/2.1.21/gems/doing-2.1.21/lib/doing/types.rb:13: warning: previous definition of InvalidExportType was here
> > /opt/homebrew/Cellar/gem-doing/2.1.21/gems/doing-2.1.21/bin/doing:30: warning: already initialized constant MissingConfigFile
> > /opt/homebrew/Cellar/gem-doing/2.1.21/gems/doing-2.1.21/lib/doing/types.rb:14: warning: previous definition of MissingConfigFile was here
> > /opt/homebrew/Cellar/gem-doing/2.1.21/gems/doing-2.1.21/bin/doing:31: warning: already initialized constant TagArray
> > /opt/homebrew/Cellar/gem-doing/2.1.21/gems/doing-2.1.21/lib/doing/types.rb:15: warning: previous definition of TagArray was here
> > /opt/homebrew/Cellar/gem-doing/2.1.21/gems/doing-2.1.21/bin/doing:32: warning: already initialized constant DateBeginString
> > /opt/homebrew/Cellar/gem-doing/2.1.21/gems/doing-2.1.21/lib/doing/types.rb:16: warning: previous definition of DateBeginString was here
> > /opt/homebrew/Cellar/gem-doing/2.1.21/gems/doing-2.1.21/bin/doing:33: warning: already initialized constant DateEndString
> > /opt/homebrew/Cellar/gem-doing/2.1.21/gems/doing-2.1.21/lib/doing/types.rb:17: warning: previous definition of DateEndString was here
> > /opt/homebrew/Cellar/gem-doing/2.1.21/gems/doing-2.1.21/bin/doing:34: warning: already initialized constant DateRangeString
> > /opt/homebrew/Cellar/gem-doing/2.1.21/gems/doing-2.1.21/lib/doing/types.rb:18: warning: previous definition of DateRangeString was here
> > /opt/homebrew/Cellar/gem-doing/2.1.21/gems/doing-2.1.21/bin/doing:35: warning: already initialized constant DateIntervalString
> > /opt/homebrew/Cellar/gem-doing/2.1.21/gems/doing-2.1.21/lib/doing/types.rb:19: warning: previous definition of DateIntervalString was here
> > ```
> >
> > Regards,
> > Daniel
> >
> >> Am 20.01.2022 um 18:05 schrieb Brett Terpstra ***@***.***>:
> >>
> >>
> >> Consider it done. When I looked at it, it turned out that after the big
> >> 2.0 refactor I never had it sorting the doing file output at all. You
> >> wouldn't notice unless you edited manually as everything is sorted in
> >> memory after reading the file, but it was just writing out the array of
> >> items as is. I changed it to sort descending by default (newest at top),
> >> but also added a config setting to change it:
> >>
> >> doing_file_sort: asc
> >>
> >> Since it doesn't make any difference what order the entries are in, only
> >> the sections, this is just a matter of convenience for users who do edit
> >> regularly.
> >>
> >> This will be available in v2.1.20, which I'll release after testing.
> >>
> >> -Brett
> >>
> >>
> >>
> >>
> >> On 20 Jan 2022, at 7:57, Daft Milk wrote:
> >>
> >>> **Is your feature request related to a problem? Please describe.**
> >>> I am doing a lot of hand-editing in the doing_file and it would very
> >>> helpful if the latest entries would be on top like I was used to with
> >>> doing v1.
> >>>
> >>> A clear and concise description of what the problem is. Ex. I'm always
> >>> frustrated when [...]
> >>> I'd like to configure doing to put the latest entries on top (sort
> >>> descending).
> >>>
> >>> **Describe the solution you'd like**
> >>> As in views configure this option to sort descending in the doing_file
> >>> itself.
> >>>
> >>> --
> >>> Reply to this email directly or view it on GitHub:
> >>> https://github.com/ttscoff/doing/issues/132
> >>> You are receiving this because you were assigned.
> >>>
> >>> Message ID: ***@***.***>
> >> —
> >> Reply to this email directly, view it on GitHub, or unsubscribe.
> >> Triage notifications on the go with GitHub Mobile for iOS or Android.
> >> You are receiving this because you authored the thread.
> >>
> >
> >
> >
> > -- 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/ttscoff/doing/issues/132#issuecomment-1018730246
> > You are receiving this because you were assigned.
> >
> > Message ID: ***@***.***>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.
> 



----------------8<---------sNip!-------------

Daniel Müller – Webdesign & Systemadministration  
Adresse:	Dresdener Straße 26, 10999 Berlin  
Web:		http://tudas.de  
Mail:		***@***.***  
Telefon: 	0049 176 12 22 22 60
