### ISSUE TITLE
doing completion errors

### ISSUE THREAD

**Issue by redmeades** [ttscoff/doing#133]
Hi, just getting into doing.

Running `doing completion` or `doing completion --type zsh --file ~/.zsh-completions/_doing.zsh` (per help) both error with:

> error: undefined method `[]' for nil:NilClass

doing v2.1.29
rbenv ruby 3.0.2p107
macos 11.6.2

**Comment by ttscoff** [comment]
Does it just immediately give you that error? Works fine for me in 
testing, but I might not be accounting for everything.

Please run:

	GLI_DEBUG=true doing completions --type zsh

and paste the output you get here.

Thanks,
Brett

**Comment by redmeades** [comment]
Hi Brett,

Yes it's is immediate. I am using omyzsh if that's of relevance.

❯ GLI_DEBUG=true doing completion --type zsh

 error: undefined method '[]' for nil:NilClass
 /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.29/lib/doing/completion/zsh_completion.rb:71:in 'parse_command': undefined method '[]' for nil:NilClass (NoMethodError)
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.29/lib/doing/completion/zsh_completion.rb:81:in 'block in parse_commands'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.29/lib/doing/completion/zsh_completion.rb:81:in 'map'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.29/lib/doing/completion/zsh_completion.rb:81:in 'parse_commands'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.29/lib/doing/completion/zsh_completion.rb:129:in 'initialize'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.29/lib/doing/completion.rb:39:in 'new'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.29/lib/doing/completion.rb:39:in 'generate_completion'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.29/bin/commands/completion.rb:25:in 'block (2 levels) in <top (required)>'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/gli-2.20.1/lib/gli/command_support.rb:131:in 'execute'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/gli-2.20.1/lib/gli/app_support.rb:296:in 'block in call_command'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.29/bin/doing:418:in 'block in <top (required)>'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/gli-2.20.1/lib/gli/app_support.rb:307:in 'call_command'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/gli-2.20.1/lib/gli/app_support.rb:83:in 'run'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.29/bin/doing:423:in '<top (required)>'
        from /Users/redmeades/.rbenv/versions/3.0.2/bin/doing:23:in 'load'
        from /Users/redmeades/.rbenv/versions/3.0.2/bin/doing:23:in '<main>'

**Comment by ttscoff** [comment]
Ok, that's getting an error when trying to parse the help output. It works flawlessly for me, also on Mac and Ruby 3, and testing from within zsh. Which makes it really hard to track down exactly what's different for you. Can you run `doing help` and `doing help again` and show me the output of each command?

I'm adding a little rescue with debugging output to help figure it out. In addition to the output above, try doing a `gem install doing` and make sure you get 2.1.30, then run `GLI_DEBUG=true doing --debug completion --type zsh` and see if you get any helpful error output from that. Helpful to me, I mean :)

**Comment by redmeades** [comment]
I'm seeing strange behaviour.

updating to 2.1.30 I get the following for both ruby 2.7.5p203 and 3.0.2p107 when running `doing completion`:

 Generating Zsh completions: [...▱...] :status!! Completion: Error parsing templates and views
!! Completion: Error parsing finishes last entry
!! Completion: Error parsing create a new one
!! Completion: Error parsing customization
error: undefined method '[]' for nil:NilClass

But, I opened a new terminal; 1st time gave above error. After running `doing help` and `doing help again` (attached) the command starting `GLI_DEBUG ...` succeeded. Then `doing completion` also succeeds.

I've realised another component - all the commands being run with the exception of the one above are within tmux.

Output of `GLI_DEBUG=true doing --debug completion --type zsh` inside tmux:

❯ GLI_DEBUG=true doing --debug completion --type zsh
>  Logging at level: debug
 Generating Zsh completions: [▱▱▱▱▱▱▱▱▱▱▱▱▱▱▱▱▱▱▱▱▱▱▱▱▱] :status>      Config: Local config files found:
>      Editor: Using /Users/redmeades/Applications/MacVim.app/Contents/bin/mvim from config 'editors.default' for default
>      Editor: Using /Users/redmeades/Applications/MacVim.app/Contents/bin/mvim from config 'editors.config' for config
>      Editor: Using /Users/redmeades/Applications/MacVim.app/Contents/bin/mvim from config 'editors.doing_file' for doing_file
>        Read: read file /Users/redmeades/NextCloud/doing.taskpaper
!! Completion: Error parsing and views
!! Completion: Error parsing last entry
!! Completion: Error parsing new one
!! Completion: Error parsing customization
error: undefined method `[]' for nil:NilClass
/Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.30/lib/doing/completion/zsh_completion.rb:92:in `block in generate_subcommand_completions': undefined method `[]' for nil:NilClass (NoMethodError)
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.30/lib/doing/completion/zsh_completion.rb:91:in `each'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.30/lib/doing/completion/zsh_completion.rb:91:in `each_with_index'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.30/lib/doing/completion/zsh_completion.rb:91:in `generate_subcommand_completions'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.30/lib/doing/completion/zsh_completion.rb:18:in `generate_helpers'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.30/lib/doing/completion/zsh_completion.rb:141:in `generate_completions'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.30/lib/doing/completion.rb:42:in `generate_completion'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.30/bin/commands/completion.rb:25:in `block (2 levels) in <top (required)>'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/gli-2.20.1/lib/gli/command_support.rb:131:in `execute'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/gli-2.20.1/lib/gli/app_support.rb:296:in `block in call_command'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.30/bin/doing:418:in `block in <top (required)>'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/gli-2.20.1/lib/gli/app_support.rb:307:in `call_command'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/gli-2.20.1/lib/gli/app_support.rb:83:in `run'
        from /Users/redmeades/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/doing-2.1.30/bin/doing:423:in `<top (required)>'
        from /Users/redmeades/.rbenv/versions/3.0.2/bin/doing:23:in `load'
        from /Users/redmeades/.rbenv/versions/3.0.2/bin/doing:23:in `<main>'

![Screen Shot 2022-02-17 at 10 54 22 am](https://user-images.githubusercontent.com/4978837/154394346-bcf1a3c5-e8b0-4a7e-b90b-ca91e50af14b.png)
![Screen Shot 2022-02-17 at 10 54 05 am](https://user-images.githubusercontent.com/4978837/154394383-7b001e09-e8f5-4c04-af1f-253ea08b3f3b.png)

**Comment by ttscoff** [comment]
Ok, I'm pushing a pre-release gem that should fix the issue. The release actually includes some major rewrites, so I didn't want to push it as a stable release quite yet. You can try it out with `gem install --pre doing`, which should get you version 2.1.31pre.

One note: I modified the `completion` command to use subcommands and arguments. It has an `install` command that will write the built-in completions to your .local folder and then offer to symlink them into an appropriate auto-load directory for your shell. Just `doing completion install zsh`. If you're not running any plugins or custom commands, that version will work fine and doesn't take 60 seconds to generate a new one. 

Generation is done with `doing completion generate SHELL`. It now automatically writes to a default file in .local and offers to symlink. You can use `--stdout` to output to STDOUT instead.

For the purpose of this ticket, though, please do test the generation in the same environment that was giving you errors before. I believe I have the issue solved. The old command should still work (tried to be backwards compatible, even though you may be the only person who's ever tried this one out…), but the new command is: 

    GLI_DEBUG=true doing completion generate --stdout zsh

Let me know if that solves it. If it works and you want to go ahead and save the generated file and load it in your shell, just remove the `--stdout` flag.

**Comment by redmeades** [comment]
Success!

The same behaviour in the 3 environments above.

Thanks for your quick work on this.

**Comment by ttscoff** [comment]
Awesome. If you use it today and run into any other issues with the 
pre-release, please do file issues. I think it's stable enough to 
publish at this point, but the changes to the underlying architecture 
make me want to test it a bit more than usual :).

Thanks,
Brett

**Comment by ttscoff** [comment]
@redmeades You probably noticed this if you tried out the zsh scripts, but the generated scripts have some pretty terrible formatting errors. I think I've corrected them and new versions are included in 2.1.33, which I'll try to push today. Curious about some feedback from someone who actually uses zsh.
