### ISSUE TITLE
Latest update causing crash

### ISSUE THREAD

**Issue by gwthompson** [ttscoff/doing#134]
**Describe the bug**

After updating to the latest version of Doing it crashes as soon as I run any doing command including doing -help

**To Reproduce**

1. Run any doing command
2. See error

Please execute the problematic command with the prefix `GLI_DEBUG=true DOING_DEBUG=true` and include the output with your bug report. E.g. `GLI_DEBUG=true DOING_DEBUG=true doing completion --type zsh`.

**Expected behavior**

Expected the help for doing to display. 

**Desktop (please complete the following information):**

 - Platform: Mac
 - OS: Monterey
 - Version 12.3 public beta 3

**Doing version**
Can't get version due to crashing.

 - Result of `doing -v`

**Ruby version**
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]

 - Result of `ruby -v`

**Additional context**
Before I updated doing -help returned the help.
[doing output.txt](https://github.com/ttscoff/doing/files/8111350/doing.output.txt)

[ruby-2022-02-21-130303.txt](https://github.com/ttscoff/doing/files/8111359/ruby-2022-02-21-130303.txt)

**Comment by ttscoff** [comment]
I’m not sure what you mean by crashing. You should at least be getting an error, and running with GLI_DEBUG=true should give you usable details.

-Brett
________________________________

**Comment by gwthompson** [comment]
I attached the terminal output to the initial report. 
[doing output.txt](https://github.com/ttscoff/doing/files/8111392/doing.output.txt)

**Comment by ttscoff** [comment]
Sorry, didn’t get the attachment in the email version. Looks like my attempt to make it more platform agnostic is causing issues. Will revert that change and push a new version later today.

- Brett

**Comment by gwthompson** [comment]
Thanks!

**Comment by ttscoff** [comment]
I guess the other thing to note is that I can no longer guarantee Ruby 2.6 compatibility (is that really what comes with Monterey still?) and am only testing on 2.7+ at this point. I made the reversion, though, so check for version 2.1.35 in a little bit and let me know if it solves the issue or not.

**Comment by gwthompson** [comment]
Version 2.1.35 solved the problem!

Thanks!

**Comment by ttscoff** [comment]
Thanks for reporting this.
