### ISSUE TITLE
Weird hash-like value at the end of each line

### ISSUE THREAD

**Issue by daftmilk** [ttscoff/doing#138]
Hey Brett,

evers since I upgrade to Monterey my tasks end with a weird bracketed hash-like value:

```
- 2022-04-25 15:40 | Doing nothing @myself @done(2022-04-25 15:41) <f89a5bcd74809b6352d6519847926d6c>
```

The "hash" is after every task, even those that are very old. What's the deal with that? Can I get rid of that?
Manually deleting doesn't help. They reappear after each new call.

Regards,
Daniel

**Comment by daftmilk** [comment]
Dear Brett,

good to know. I will just have to edit some of my RexExps using with doing. Keeping track of my things since 2007.



Regards,
Daniel

----------------8<---------sNip!-------------

Daniel Müller – Webdesign & Systemadministration  
Adresse:	Dresdener Straße 26, 10999 Berlin  
Web:		http://tudas.de  
Mail:		***@***.***  
Telefon: 	0049 176 12 22 22 60

**Comment by ttscoff** [comment]
Well, for the sake of a regex, the id will always be at the end of the 
line, preceded by a space, surrounded by angle brackets, 32 characters, 
lowercase letters and numbers. Here's the new regex that Doing uses when 
parsing:

https://github.com/ttscoff/doing/blob/develop/lib/doing/wwid/filetools.rb#L43

-Brett

**Comment by daftmilk** [comment]
Dear Brett,

thank you very much for your reply, especiall for looking up the regex.

You wrote:

> It shouldn’t be that hard to edit around, though, and the whole point is to move Doing toward being usable > without ever needing to manually edit the file.

However wasn't that the whole point of the whole text-files-movement? markdown, taskpaper, etc.
To keep it very readable? You are introducing another change of the syntax.

- Will doing respect tags I add manually after the unqiue id?
- Why is the new unique id not a "tag with argument" like @done(2022-02-28 09:51)
- I have always wondered why the starting time is not a tag (e.g. @start(2022-02-28 09:51) like @done.

Regards,
Daniel

**Comment by ttscoff** [comment]
> However wasn't that the whole point of the whole text-files-movement? markdown, taskpaper, etc.
> To keep it very readable? You are introducing another change of the syntax.
It’s still a plain text file, and easily human readable. I’m willing to reconsider the ID format, but it didn’t really affect the editability of the file, nor its ability to be recognized by any taskpaper parser.
> - Will doing respect tags I add manually after the unqiue id?
No, adding tags after the id will probably break it and result in a new id being appended. All of doing’s tagging functions will respect this.
> - Why is the new unique id not a "tag with argument" like @done(2022-02-28 09:51)
Because Doing has pretty extensive tag handling and I want an id that can be easily identified and NOT displayed by doing display functions.
> - I have always wondered why the starting time is not a tag (e.g. @start(2022-02-28 09:51) like @done.
Same as above. Every item requires a start time, but the done time is optional. To me it only makes sense to make it part of the file format.

If you just want a command line TaskPaper Utility, there are other options out there. Doing strives to use plain text in more structured ways than what seems to suit your needs …


- Brett

**Comment by daftmilk** [comment]
Dear Brett,

those where just wonderings of mine.

Doing is awesome. It saves me a lot of time and increases my earnings.
My billing-system is based on it.

Thank you for your awesome work!
I will keep supporting you with a small monthly sum.

Regards,
Daniel


> Am 28.04.2022 um 14:03 schrieb Brett Terpstra ***@***.***>:
> 
> 
> > However wasn't that the whole point of the whole text-files-movement? markdown, taskpaper, etc.
> > To keep it very readable? You are introducing another change of the syntax.
> It’s still a plain text file, and easily human readable. I’m willing to reconsider the ID format, but it didn’t really affect the editability of the file, nor its ability to be recognized by any taskpaper parser.
> > - Will doing respect tags I add manually after the unqiue id?
> No, adding tags after the id will probably break it and result in a new id being appended. All of doing’s tagging functions will respect this.
> > - Why is the new unique id not a "tag with argument" like @done(2022-02-28 09:51)
> Because Doing has pretty extensive tag handling and I want an id that can be easily identified and NOT displayed by doing display functions.
> > - I have always wondered why the starting time is not a tag (e.g. @start(2022-02-28 09:51) like @done.
> Same as above. Every item requires a start time, but the done time is optional. To me it only makes sense to make it part of the file format.
> 
> If you just want a command line TaskPaper Utility, there are other options out there. Doing strives to use plain text in more structured ways than what seems to suit your needs …
> 
> 
> - Brett

**Comment by ttscoff** [comment]
Thanks. I didn’t mean to sound crabby, I just responded before I had coffee and put my manners on :).

- Brett
