### ISSUE TITLE
`doing config` not using my EDITOR?

### ISSUE THREAD

**Issue by jafish** [ttscoff/doing#139]
Platform: macOS version 12.3.1
Results of `ruby -v`: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]`

I'm using fish shell, version 3.4.1, and have my editor set to bbedit (`echo $EDITOR` returns `bbedit`). `doing config` still opens the default VIM on my system. `doing config --editor bbedit` does what I want, so I made an alias for that command, but still wondering why `doing config` seems to ignore the `$EDITOR` variable.

**Comment by ttscoff** [comment]
Do you have a default editor in a .gitconfig file? Git editor config 
trumps $EDITOR. You can, of course, manually specify an editor in the 
config file itself in editors.config.

---
editors:
   config: bbedit


-Brett

**Comment by jafish** [comment]
Thanks, I don't have an $EDITOR defined in a .gitconfig, but I wasn't aware of the ability to set that in the configuration file. Now `doing config` works as expected—it's a good workaround for what might be a hard to diagnose issue.
