### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mckeehan** [ttscoff/doing#140]
**Describe the bug**

`doing now -f` "finishes" different tasks than `doing finish` would do.

**To Reproduce**

Compare Scenario 1 with Scenario 2:

Scenario 1:
1. Create a "meanwhile" task.
2. Start TASK A.
3. When finished with task a, use `doing now -f` to finish TASK A and start TASK B.
4. Observe that the "meanwhile" task is the task which is marked @done

```bash
$ doing meanwhile -s TimeSheet Client One
    New entry: added " 4:54am: Client One @meanwhile" to TimeSheet

$ doing now @clientone TASK A
    New entry: added " 4:54am: project b" to Currently

$ doing now -f @clientone TASK B
    New entry: added " 4:54am: project c" to Currently
       Tagged: @done added to 1 item

$ doing today
 4:54am: TASK A                                                                           [Currently ]  
 4:54am: TASK B                                                                           [Currently ]  
 4:54am: Client One @meanwhile @done(2022-05-04 04:54)                                    [TimeSheet ]  
```

Scenario B:
1. Create a "meanwhile" task.
2. Start TASK A.
3. Finish TASK A
4. Start TASK B.
5. Observe that TASK A is the task which is marked @done

```bash
$ doing meanwhile -s TimeSheet Client One
    New entry: added " 5:03am: Client One @meanwhile" to TimeSheet

$ doing now TASK A
    New entry: added " 5:03am: TASK A" to Currently

$ doing finish
       Tagged: added tag @done to TASK A @done(2022-05-04 05:03)

$ doing now TASK B
    New entry: added " 5:03am: TASK B" to Currently

$ doing today
 5:03am: Client One @meanwhile                                                            [TimeSheet ]  
 5:03am: TASK A @done(2022-05-04 05:03)                                                   [Currently ]  
 5:03am: TASK B                                                                           [Currently ]  

```

**Expected behavior**

I would expect the outcome in both scenarios to be the same and I would expect that `doing now -f` would behave just like the sequence of two commands `doing finish` followed by `doing now`.

**Desktop (please complete the following information):**

 - Platform: [e.g. Mac, Linux] Mac
 - OS: [e.g. Monterrey, Unbuntu]  Monterrey
 - Version [e.g. 22] 12.3.1 (21E258)

**Doing version**

 - Result of `doing -v`
 - doing version 2.1.26

**Ruby version**

 - Result of `ruby -v`
 - ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]

**Additional context**

**Comment by ttscoff** [comment]
It appears to be grabbing the first unfinished task rather than the most 
recent one, which does seem backward.

Question: in your opinion, if you use the -f switch with `doing now`, 
would you expect it to finish the last _unfinished_ entry, or only 
affect the _last_ entry, ignoring it if it's already marked @done?

-Brett

**Comment by mckeehan** [comment]
I think I would expect it to only affect the _last_ entry (ideally or optionally in the same section), ignoring it if it's already marked @done

**Comment by ttscoff** [comment]
Cool, will update with this functionality next time I have a chance to sit down and do some coding on it.

-Brett

**Comment by mckeehan** [comment]
Works as expected now!
