### ISSUE TITLE
Cmd doing config list does not detect configuration file

### ISSUE THREAD

**Issue by krzysiek-b** [ttscoff/doing#143]
**Describe the bug**

I'm using WSL (ubuntu on windows) and seems previous configuration worked as expected. I was using my local windows system on linux and run doing on ubuntu. I was using v 1.0.41. Current version seems not detect configuration file from windows file system or there is something else I did not found in the docs.

**To Reproduce**

Place your config.yml on windows file system and run `doing config list` to see if it is properly detected
What I did was this
```
user@host:/mnt/c/Folder$ doing config list

/home/user/.config/doing/config.yml
user@host:/mnt/c/Folder$ ls *yml
config.yml
```

When I try remove .config folder it gets created when calling `doing config list`
```
user@host:/mnt/c/Folder$ rm -R /home/user/.config/doing
user@host:/mnt/c/Folder$ doing config list
>  Config directory created at /home/user/.config/doing

/home/user/.config/doing/config.yml
       Config: Config file doesn't exist, using default configuration
>      Config: Config file written to /home/user/.config/doing/config.yml
```

`DOING_CONFIG` env variable is not used.

I'm not sure if this is connectd but when I use env var i get this. Was the file system APi changed during refactor or I do miss something here?
```
user@host:/mnt/c/Folder$ export DOING_CONFIG=/mnt/c/Folder
user@host:/mnt/c/Folder$ doing config list

/mnt/c/Folder
!!     Config: Error reading default configuration
!!      Error: Is a directory @ io_fillbuf - fd:7 /mnt/c/Folder
```

**Expected behavior**

I expect the local file to be found and used by doing.

**Desktop (please complete the following information):**

 - Platform: Windows/WSL
 - OS: [Unbuntu]

**Doing version**

 - 2.1.47

**Comment by ttscoff** [comment]
Local config files are named .doingrc. Only the config in the base .config directory is called config.yml. Does that help, or am i  misunderstanding you?

**Comment by krzysiek-b** [comment]
I think this makes sense. I understood all new configuration is not stored in config.yml and they are inherited like .doingrc were and the .dointrc are no longer used. Thanks

**Comment by ttscoff** [comment]
I left the local configs as dot files to make them invisible, as well as easy to .gitignore in a universal ignore file.

**Comment by krzysiek-b** [comment]
I checked and .doingrc are properly detected so we can close this issue as it is invalid.
