### ISSUE TITLE
Os locale are not used when listing dates

### ISSUE THREAD

**Issue by krzysiek-b** [ttscoff/doing#144]
**Describe the bug**

My locale are set to Polish and ubuntu seems to act right. Doing is still using EN.

What I get when calling eg. `ls /tmp -l` is
<img width="214" alt="image" src="https://user-images.githubusercontent.com/6192236/167377386-e72e3daf-46fe-41c2-9b62-e0b375f34883.png">

Doing still uses EN
<img width="80" alt="image" src="https://user-images.githubusercontent.com/6192236/167377461-86bdef71-1d85-4f73-94bd-f136af9eab1a.png">

**To Reproduce**

Enable other locales on Ubuntu.
Use any doing listing command like `doing show`

**Expected behavior**

Doing should display dates using os selected locales.

**Comment by ttscoff** [comment]
I'm not sure how to fix this. Date formatting just uses the date_format config string and Ruby's strftime. If it's not respecting locale, that seems like it would be a Ruby issue. If you find any documentation that shows a way to get strftime to respect locale in your case, please let me know.

**Comment by krzysiek-b** [comment]
I'm not a Ruby expert but here's something which looks promising

https://stackoverflow.com/questions/18593661/how-do-i-strftime-a-date-object-in-a-different-locale

**Comment by ttscoff** [comment]
Sorry to let this sit for TWO YEARS, but upon re-reading it I realize that the issue is that the date formats are hardcoded. You can modify any of them using templates. See https://github.com/ttscoff/doing/wiki/Templates#date-formatting

**Comment by krzysiek-b** [comment]
No problem, I understand both so this is not a big issue. Take your time :)
