### ISSUE TITLE
How to make tags colored when using show/last/today

### ISSUE THREAD

**Issue by krzysiek-b** [ttscoff/doing#145]
Seems the template contains `title` which contains tags. My goal would be to color the tags in same manner theya re colored when adding new entry (orange?).

Is there any template tag I can use to spearatelly display title and its tags ?

<img width="396" alt="image" src="https://user-images.githubusercontent.com/6192236/167611732-20675e34-3d4a-4475-bf79-6855b928773b.png">

**Comment by ttscoff** [comment]
If you set `tags_color` in the root config or in any template (default in this case), it should highlight tags. Set it to any color name that the template engine recognizes (see `doing colors`). 

There is a %tags placeholder, but there's not one that shows a title *minus* tags.

**Comment by krzysiek-b** [comment]
Perfect, thanks!

**Comment by krzysiek-b** [comment]
I think we have a small bug here. This seems to work as expected for `today` but when I use `last` the first tag is not using colors. Maybe the regex pattern does not catch it. My entry was done like this `doing now @tagA @tagB text text text` and @tagA was not using colors for `doing last`

**Comment by ttscoff** [comment]
This will take some digging and I won't get to it for a while. If you know a little bit of Ruby, feel free to dig into source and see if you can find the issue. Otherwise I hope to find time to look at it in a week or so.

**Comment by ttscoff** [comment]
The last command provides colorized tags for me...

![](https://share.cleanshot.com/kgCgUB+)

I'm not sure why you wouldn't be getting them. The other tags in the entry are colored?

**Comment by krzysiek-b** [comment]
The problem exists always on my side and it might be connected with me using Ubuntu on Windows. I will try use it directly on Windows or Ubuntu and let you know if you're interested?
