### ISSUE TITLE
`doing again` using `confirm_longer_than` even if entry is already @done

### ISSUE THREAD

**Issue by jafish** [ttscoff/doing#146]
**Describe the bug**

When running `doing again`, if I choose to repeat an entry whose completion time exceeds the value of `confirm_longer_than`, `doing` asks `Did this entry actually take x hours, y minutes [Y/n]?` even if the entry being repeating already has a `@done` tag with a timestamp.

**To Reproduce**

1. Execute command `doing again`, with the most recent task's completed timestamp longer ago than the value of `confirm_longer_than`.
2. See the prompt asking to confirm the time.

Please execute the problematic command with the prefix `GLI_DEBUG=true DOING_DEBUG=true` and include the output with your bug report. E.g. `GLI_DEBUG=true DOING_DEBUG=true doing completion --type zsh`.

>      Config: Local config files found:
>      Config: translated key path paginate to paginate
>      Config: translated key path disabled_commands to disabled_commands
>      Config: translated key path editors to editors
>      Editor: Using bbedit -w from config 'editors.default' for default
>      Config: translated key path search.case to search.case
>      Config: translated key path tag_sort to tag_sort
>      Editor: Using bbedit from config 'editors.config' for config
>      Config: translated key path editors.config to editors.config
>      Editor: Using taskpaper from config 'editors.doing_file' for doing_file
>      Config: translated key path current_section to current_section
>      Config: translated key path plugins.command_path to plugins.command_path
>      Config: translated key path doing_file to doing_file
>      Read: read file /Users/jafish/Library/Mobile Documents/com~apple~CloudDocs/NVNotes/taskx-Main.taskpaper
>      Filtered: Parameters matched 44 entries
>      Config: translated key path interaction.confirm_longer_than to interaction.confirm_longer_than
>      Tag: added @done to "Learning Assistant Proposal @admin @curriculum @done(2022-05-11 20:22) @alternate-assignment @chair"
    New entry: added " 5:10am: Learning Assistant Proposal @admin @curriculum @alternate-assignment @chair" to Currently
>      Config: translated key path doing_file_sort to doing_file_sort
>      Config: translated key path backup_dir to backup_dir
>      Config: translated key path history_size to history_size
>      Write: File written: /Users/jafish/Library/Mobile Documents/com~apple~CloudDocs/NVNotes/taskx-Main.taskpaper

**Expected behavior**

I expect the confirmation dialog to appear only if the chosen task to repeat does not already have an end timestamp. 

**Desktop (please complete the following information):**

 - Platform: Mac
 - OS: Monterey
 - Version: 12.3.1

**Doing version**

 - 2.1.47

**Ruby version**

 - ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]

**Additional context**

Maybe this is a misunderstanding of how `confirm_longer_than` is supposed to work, but my assumption was that it would be invoked only when a task is still "open".

**Comment by ttscoff** [comment]
Fixed in 2.1.49, available to `gem install doing` now. Let me know if the fix doesn't solve it for you.
