### ISSUE TITLE
[FEATURE REQUEST] add support for i[:flagged] in markdown export

### ISSUE THREAD

**Issue by mckeehanheadwire** [ttscoff/doing#150]
**Is your feature request related to a problem? Please describe.**

I want to be able to show flagged items when exporting data to markdown.

**Describe the solution you'd like**

Currently in the markdown exporter, I can do `i:[done]` to get an x for when something is done, I'd like similar functionality to identify items that have been flagged.

**Describe alternatives you've considered**

**Additional context**

**Comment by ttscoff** [comment]
I'm not familiar with the `i:[done]` syntax. Is this something you're adding manually in a template? And where would it be applied by the export?

**Comment by mckeehanheadwire** [comment]
Type-o on my part the syntax that I'm referring to is `i[:done] ` which just puts an x if the task is marked as done. Used in this template:

```
<% @items.each do |i| %>
- [<%= i[:done] %>]  <%= i[:shortdate] %> **<%= i[:title] %>** <% if i[:time] && i[:time] != "00:00:00" %>[<%= i[:time] %>]<% end %><% if i[:note].length.positive? %><%= "\n    - " + i[:note].map{|n| n.strip }.join("\n    - ") %><% end %><% end %>
```

**Comment by ttscoff** [comment]
Ok, `i[:flagged]` is now set to true or false for each item, meaning you can do `<% if i[:flagged] %>🚩<% end %>`. Not sure exactly what you want to do with that in a Markdown list, but I'd be curious how you use it.

**Comment by ttscoff** [comment]
It should be present in 2.1.56. Do you have the custom template saved and referenced in the config? Also, just noticed that my deploy pipeline hung up and 2.1.56 hadn't published to the gem server yet, so maybe make sure you've actually got 2.1.56.

**Comment by ttscoff** [comment]
I'm going to add `i[:finished]` which will be true or false. Right now `i[:done]` is either x or space, so `finished` will let you do a conditional where `<% if i[:finished] %>x<% end %>` would work. I'll leave `:done` as is for compatibility.

**Comment by ttscoff** [comment]
Just release 2.1.57 which I can confirm works with `if i[:flagged]`. Let 
me know if you still don't see it functioning.

**Comment by mckeehanheadwire** [comment]
I can confirm that 2.1.57 has both the i[:flagged] and i[:finished] working.

Thank you very much.

**Comment by ttscoff** [comment]
So what would the template do if flagged was true? Essentially you could test for `i[:title] =~ ***@***.***/` (depending on the marker_tag setting) and insert markup based on that, but I'm not sure how you would "flag" something in Markdown.

**Comment by mckeehanheadwire** [comment]
I'm using the output to feed into a Markdown file that I view in Obsidian. I'm building a bulleted list where the bullets are different depending on what the thing is (see https://github.com/kepano/obsidian-minimal/releases/tag/5.1.8)

Here's my current template...btw, this feature has already been implemented...

```
## <%= @page_title %><% @items.each do |i| %>
- [<% if i[:section] == "Travel Calendar" %>l<% elsif i[:section] == "Later" %>I<% elsif i[:title].include? "@meeting" %><<% elsif i[:finished] %>x<% elsif i[:flagged] %>*<% else%>/<% end %>] <%= i[:shortdate] %><% if i[:end_date] != " " %> - <%= i[:end_date] %><% end %> : <%= i[:title] %> <% if i[:time] && i[:time] != "00:00:00" %>[<%= i[:time] %>]<% end %><% if i[:note].length.positive? %><%= "\n    - " + i[:note].map{|n| n.strip }.join("\n    - ") %><% end %><% end %><%= @totals %>
```

**Comment by ttscoff** [comment]
Yep, the current version of Doing supports the following parameters for @items

- date
- shortdate
- flagged
- done
- finished
- note
- section
- time
- title
