### ISSUE TITLE
Summary table layout seems to be not correct for smaller values

### ISSUE THREAD

**Issue by krzysiek-b** [ttscoff/doing#152]
**Describe the bug**

<img width="112" alt="image" src="https://user-images.githubusercontent.com/6192236/171353631-113cc428-039e-4258-9ccb-eeadfae43625.png">

**Comment by ttscoff** [comment]
confirmed, will see what I can do about that a year later. Sorry for the delayed reply.

**Comment by krzysiek-b** [comment]
Thanks, this is not as much important so no worries :)

**Comment by ttscoff** [comment]
I _think_ this is fixed so closing for now.
