### ISSUE TITLE
[BUG] Using "doing now" flattens identions in taskpaper file

### ISSUE THREAD

**Issue by dskesler** [ttscoff/doing#155]
If I have a taskpaper file which has indented items in the outline, when I add a item by running command "doing now <some new text>", the taskpaper file flattens the indented items to be on the same outline level as all other items.
For example, file contains:
```
Topic:
      - item 1 
      - item 2
```
When I add an item from the command line using "doing now New topic" command, when I return to the file, I see this:
```
New topic
Topic:
- item 1 
- item 2
```

The indention of items 1 and 2 are removed and the entire list is flattened into the same outline level.

**Expected behavior**
I expected the indented outline levels to remain even after adding new item.

**Desktop (please complete the following information):**

 - Platform: Mac
 - OS: Monterey
 - Version: 12.5

**Doing version**

1.0.35

**Ruby version**

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]

**Comment by ttscoff** [comment]
Doing is not designed to work with TaskPaper files that are used for 
other purposes. A "doing file" has to follow a strict format, and will 
automatically adjust itself to fit that format.

You can edit a doing file with TaskPaper, but it's not designed as a 
TaskPaper integration.

-Brett

**Comment by dskesler** [comment]
Thanks for that clarification. I'll close this.

**Comment by ttscoff** [comment]
By the way, if you just want a fast way to add/modify TaskPaper files from the command line, I recently souped up my `na` project for just that purpose. https://github.com/ttscoff/na_gem/
