### ISSUE TITLE
[BUG] "later" documentation & inclusion

### ISSUE THREAD

**Issue by masukomi** [ttscoff/doing#157]
**Describe the bug**
from a documentation perspective `doing later` appears to be a valid command. 

In practice, it is not. `doing_entry_test.rb` has a comment that says 

>   The later command is now optional and not included by default

It is not clear what one has to do to include this, optional feature, or if that's actually possible.

**To Reproduce**

1. Execute command: `doing later foo`
2. See error: foo is not added to the later section as documentation claims.

as this is really a documentation bug not a "it blew up" bug i've not filled in all the error catching code things. 

I don't know if the solution is "remove documentation about 'later'" or "move it to an optional section along with instructions about enabling it" but... either way. I ended up with 4 "current" tasks when trying to start using this and it's not at all what i wanted / expected. 

**Doing version**

 - Result of `doing -v`
doing version 2.1.69

**Comment by ttscoff** [comment]
I removed a bunch of redundant commands. Originally later was supposed 
to be able to be added back with `doing commands add` but it looks like 
I totally canned it and never updated docs. I'll remedy that (or feel 
free to make edits on the wiki for me).

For the record, you can just run `doing now -s later foo` to add an 
entry to the Later section (optionally including a @later tag). You're 
not the first person to ask about that missing command, though, so it 
might be worth reimplementing it.

-Brett

**Comment by ttscoff** [comment]
I'll document this as requested:

Save [this 
command](https://github.com/ttscoff/doing/blob/master/lib/examples/commands/later.rb) 
to ~/.config/doing/commands/later.rb and it should enable the command 
for you.

-Brett

**Comment by masukomi** [comment]
just figured that out and was going to update this.

My thinking after adding it and running it is that... whatever form the docs take re running it should have the big asterisk that you can't actually see the "later" things except via `doing select` 

So, I'm thinking that in the current state it's more of a "here's a good starting point for you to play with" than a "optional feature" because anything you create via it seems pretty hidden. This is of course, my total newb perspective re this tool.

**Comment by masukomi** [comment]
update: 

just found `doing show Later` 

which.... is "good" in that now i can see the Later stuff without adding code, but "bad" in that we have the non-optional command `show` telling you you can do things that are coming from a section created by an optional command. 

I'm thinking that shouldn't be in the `show` examples, but it raises the question of how do commands that alter the structure in such a way as to change / add to "show"'s options convey that information to the user?

**Comment by ttscoff** [comment]
All entry commads allow you to specify a section, and sections can be 
called anything you want. `doing show SECTION` will display any section 
you've created, whether manually or with a command like `later`. The 
point of the example is to demonstrate this using a common section 
title, not one that's expected to be present.

-Brett
