### ISSUE TITLE
How to make a custom view where time and entries are grouped

### ISSUE THREAD

**Issue by krzysiek-b** [ttscoff/doing#161]
Hi,

What I was looking for is a simple view to fast see how many hours I have logged in last few days. Day total and sum. So I was thinkling a view like this would be helpful.

```
+------------+----------+-----------+
| date       | Summary  | Time      |
+------------+----------+-----------+
| 09.02.2023 | X...     |    0h 10m |
|            | Y...     |           |
| 10.02.2023 | Z...     |    0h 20m |
...
+------------+----------+-----------+
|                     Total: 0h 30m |
+------------+----------+-----------+
```

What would be the best way to do this? New implementation or maybe a plugin?

**Comment by ttscoff** [comment]
Yeah, this could ostensibly be done with an export plugin, which would 
allow you something like `doing show --since "7 days ago" -o 
dailytotals` (where dailytotals is a plugin that collated durations by 
day and output the table you're looking for).

Another possiblity is to use the built-in JSON output, which includes 
date and duration info, and build an external tool to display in any 
format you wanted to.

I think this is a valid feature request, so if I get some time to play 
with it, I may create the plugin version of it and include it, but no 
promises.

-Brett

**Comment by ttscoff** [comment]
I got bored and played with it. Pushed a new version of the gem that 
includes 'byday' as an export plugin, so you can use `-o byday` with any 
output command to get a table similar to what you're requesting. Feel 
free to futz with the code and submit changes via PR:

https://github.com/ttscoff/doing/blob/develop/lib/doing/plugins/export/byday.rb

You can test it out by either `gem update doing` for the latest release, 
or just copying that plugin to ~/.config/doing/plugins. If you're going 
to do any development on it, I'd recommend installing in plugins and 
editing from there.

-Brett

**Comment by krzysiek-b** [comment]
You're superfast and it looks great and its super useful. Thank you!

**Comment by krzysiek-b** [comment]
I would like to suggest few changes to this:
- Add option to limit the number of characters printed in the summary column - this one seems to be most required as my console seems to be not so large as yours :)
- remove the @done tag as it seems to be not so much useful here
- Maybe add headers for somone who would like to print this to get a better feeling whats inside

If you like me to do a PR please let me know.

**Comment by ttscoff** [comment]
Pushing a new version that handles most of these (and adds some color 
when writing to terminal). I can't allow control of the summary width, 
that has to be hardcoded in a plugin (but I did reduce it by about 30 
characters, let me know if it fits for you). The other option here would 
be to make an HTML table that could be opened in the browser...

-Brett

**Comment by ttscoff** [comment]
Oh duh, I totally forgot I added the ability for plugins to have 
configuration items. I can add the variable width in in the next update.

**Comment by ttscoff** [comment]
Ok, now you can configure the width by adding:

```
plugins:
   hidden_commands: []
   byday:
     item_width: 50
```

To your config file with whatever width you want. 2.1.78 deploying now.

-Brett

**Comment by krzysiek-b** [comment]
Small issue here but works like a charm. Thank you!
<img width="178" alt="image" src="https://user-images.githubusercontent.com/6192236/224492579-0a8b81e5-1aee-424b-8e7f-2ad885f1ccdb.png">

**Comment by ttscoff** [comment]
Fixing!

Thanks,
Brett
