### ISSUE TITLE
[BUG] Installation fails - ruby Version on macOS 13.4

### ISSUE THREAD

**Issue by FloCola** [ttscoff/doing#162]
Installation fails. Error:

```
ERROR:  Error installing /Users/mars/Library/Caches/Homebrew/doing-2.1.80.gem:
	rouge requires Ruby version >= 2.7. The current ruby version is 2.6.10.210.
```

**To Reproduce**
Did nothing with Ruby before on this System. A while back, maybe macOS 12, 13.1 it did install without issues afai remember.

1. Execute command `brew install brew-gem` `brew gem install doing`

**Desktop (please complete the following information):**

 - Platform: [mac]
 - OS: [macOS Ventura]
 - Version [13.4]

**Doing version**

 - Result of `doing -v` -> not installed

**Ruby version**

 - Result of `ruby -v`
    `ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]` 

**Additional context**

- With 2 years, i am a newb at macOS. Had nothing to do with python, ruby, java. It is sometimes a riddle to me... :(
- i tried:
    ```
   gem update          
   gem cleanup
   gem update --system
    ```
Using `sudo gem update --system` gives me a permission error, maybe because of readonly OS partition? idk..

Do i need to install brew version of ruby? After that, there is sure some fiddle about Paths/Env. I am sure google will ultimately help. But maybe you got the correct way for it.

**Comment by ttscoff** [comment]
If you don’t need other versions of Ruby available for anything else, then yes, update Ruby through homebrew. Should be pretty painless.

- Brett

**Comment by FloCola** [comment]
yea that worked with the export path. Thanks.
