### ISSUE TITLE
[FEATURE REQUEST] Allow customization of %shortdate

### ISSUE THREAD

**Issue by tophee** [ttscoff/doing#163]
**Is your feature request related to a problem? Please describe.**

I want to use the 24h time format, so the first thing I did after installing was to remove all the `%I` and `%P` formatting, but to my surprise, doing kept using 12h time. I then figured out that this behaviour is apparently backed into `%shortdate`, so, given that you're allowing customization for long dates, I'm wondering whether `%shortdate`could also be opened up for customization.

**Describe the solution you'd like**

A basic solution would probably be to provide two switches for the `%shortdate` format, one for switching between 12h and 24h time, and one for switching between M/D and D/M format.

But I guess the "proper" solution would be to provide a `shortdate_format` string, just like there is `date_format` for `%date`. In fact, we probably need four such options: `shortdate_format_today`, `shortdate_format_thisweek`, `shortdate_format_thismonth`, `shortdate_format_thisyear` 

**Describe alternatives you've considered**

see above

**Comment by ttscoff** [comment]
I don't hate this idea. It's a lot of extra config options, but we're 
kind of past the point of no return on the size of the config file these 
days. In version 2.1.84 (available now, `gem install doing`) there are 
new config options at the root level:

```
shortdate_format:
   today:
   this_week:
   this_month:
   older:
```

Run `doing config update` to add them to your config file with defaults 
that you can edit (`doing config edit`).

Tests are passing, I think this is complete. If you get a chance to test 
it out, let me know and close the issue if it works for you.

-Brett

**Comment by tophee** [comment]
You are amazing! I submit quite a few bug reports and feature requests, but never have I seen this kind of speedy response! And that was for a feature that you "don't hate". I don't dare to imagine what happens with a feature request that you like. 🤩

Anyway, the new setting seem to work for me (still testing out the app, though).

Thanks a lot!
