### ISSUE TITLE
doing later - Unknown Command

### ISSUE THREAD

**Issue by maxihaindl** [ttscoff/doing#169]
Hey there, 

I just stumbled across your tool and I love it! <3
But I am wondering why `doing later` is not available on my system.

I installed `doing` version 2.1.84 on my macbook-pro Sonoma 14.4 with `brew` version 4.2.15 but `doing later` is not available

```
maximilian.haindl@tuerbookpro:~$ doing later test123
!! Unknown Command: later
maximilian.haindl@tuerbookpro:~$ doing --version
doing version 2.1.84
maximilian.haindl@tuerbookpro:~$ uname -a
Darwin tuerbookpro.loc 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:43 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6000 arm64
maximilian.haindl@tuerbookpro:~$ brew --version
Homebrew 4.2.15
```

Any Ideas?

**Comment by ttscoff** [comment]
`later` was removed as a default command (I guess I still haven't 
updated the docs). It's the same as running `doing now --section Later 
...` and in its present state was a bit redundant as anything but a 
shortcut. However, you can easily add it back in as a plugin. The source 
for the plugin is 
[here](https://github.com/ttscoff/doing/blob/master/lib/examples/commands/later.rb), 
and you can find instructions 
[here](https://github.com/ttscoff/doing/wiki/Adding-Commands). It takes 
just a minute to create the plugins directory and drop the file in 
there, and you'll have a `later` command.

-Brett

**Comment by ttscoff** [comment]
`later` was removed as a default command (I guess I still haven't 
updated the docs). It's the same as running `doing now --section Later 
...` and in its present state was a bit redundant as anything but a 
shortcut. However, you can easily add it back in as a plugin. The source 
for the plugin is 
[here](https://github.com/ttscoff/doing/blob/master/lib/examples/commands/later.rb), 
and you can find instructions 
[here](https://github.com/ttscoff/doing/wiki/Adding-Commands). It takes 
just a minute to create the plugins directory and drop the file in 
there, and you'll have a `later` command.

**Comment by ttscoff** [comment]
It would actually make sense to modify the command to be called `todo` and have it add a tag like `@todo` when creating new entries. Then you could easily check your todo list with `doing show @todo`, and use the `begin` command to reset the start date when you start working on a todo item. Something I might look into, but I haven't dug into Doing for a while as it is, by and large, bug free enough to let me work on other projects :)

**Comment by ttscoff** [comment]
Updated the docs to remove the inference that `later` was available as a default command. I only saw it mentioned in [Adding Entries](https://github.com/ttscoff/doing/wiki/Adding-Entries). Was there somewhere else you got the impression it was available?

**Comment by ttscoff** [comment]
Added a `todo` command to the same examples folder as the later command in the repo. Closing this for now, let me know if you have any questions.
