### ISSUE TITLE
Day One digest entries out of a doing today

### ISSUE THREAD

**Issue by mrjcleaver** [ttscoff/doing#64]
Re: https://github.com/ttscoff/doing#what-and-why

> Side note: I actually use the library behind this utility as part of another script that mirrors entries in Day One that have the tag "wwid." I can use the hourly writing reminders and enter my stuff in the quick entry popup. Someday I'll get around to cleaning that up and putting it out there.
> & 
> https://github.com/ttscoff/doing/issues/52

It'd be nice if you could share that.

Thanks, M.

**Comment by ttscoff** [comment]
7 years later I have written a dayone plugin for Doing for anyone who's still interested. https://github.com/ttscoff/doing/wiki/Exporting-to-Day-One
