### ISSUE TITLE
Doing errors with Ruby 2.2.2

### ISSUE THREAD

**Issue by aviris** [ttscoff/doing#70]
Upgraded to Ruby 2.2.2 and get the following error when trying to setup or run doing (1.0.8Pre).
Switching back to Ruby 2.2.0 it works perfectly again. I've tried on two different machines (one 10.10.3, one 10.10.4).The 10.10.4 machine was fresh install (no 2.2.0 first) and no doing.rc. I have no experience with Ruby other than doing, so I just installed 2.2.0 and Doing works fine again. Thought I'd report it though.

---

> doing -config
> /Users/aviris/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- gli (LoadError)
>     from /Users/aviris/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
>     from /Users/aviris/.rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/doing-1.0.8pre/bin/doing:2:in `<top (required)>'
>     from /Users/aviris/.rubies/ruby-2.2.2/bin/doing:23:in`load'
> ##     from /Users/aviris/.rubies/ruby-2.2.2/bin/doing:23:in `<main>

**Comment by ttscoff** [comment]
did you update the gem? uninstall and run `gem install doing --pre` 
again, should automatically install the dependencies (including gli).
