### ISSUE TITLE
Error with 1.0.8pre

### ISSUE THREAD

**Issue by ansonlos** [ttscoff/doing#73]
I just install 1.0.8pre on my Mac OS X 10.10.5 and I'm getting the following error message:

    $ doing now Test
    $ error: undefined method `[]' for nil:NilClass

This is what I get with `GLI_DEBUG=true doing now Test`:

    /Library/Ruby/Gems/2.0.0/gems/doing-1.0.8pre/lib/doing/wwid.rb:1256:in `autotag': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/doing-1.0.8pre/lib/doing/wwid.rb:351:in `add_item'
	from /Library/Ruby/Gems/2.0.0/gems/doing-1.0.8pre/bin/doing:86:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/gli-2.9.0/lib/gli/command_support.rb:121:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/gli-2.9.0/lib/gli/command_support.rb:121:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/gli-2.9.0/lib/gli/app_support.rb:284:in `block in call_command'
	from /Library/Ruby/Gems/2.0.0/gems/gli-2.9.0/lib/gli/app_support.rb:297:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/gli-2.9.0/lib/gli/app_support.rb:297:in `call_command'
	from /Library/Ruby/Gems/2.0.0/gems/gli-2.9.0/lib/gli/app_support.rb:79:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/doing-1.0.8pre/bin/doing:1058:in `<top (required)>'
	from /usr/bin/doing:23:in `load'
	from /usr/bin/doing:23:in `<main>'

And `ruby -v` shows:

    ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

**Comment by ttscoff** [comment]
See #58

**Comment by ansonlos** [comment]
Yep, #58 nailed it. 

Thanks!
