### ISSUE TITLE
Doing error: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by fortunatas** [ttscoff/doing#74]
Hi,
Getting error "undefined method `[]' for nil:NilClass" after entering in terminal 'doing now whatever text'. Any ideas? Thanks!
Mac OS X 10.10, ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

Fortunatas

**Comment by vcavallo** [comment]
Hi. Check out #58  - might help.

**Comment by fortunatas** [comment]
Hi vcavallo!
