### ISSUE TITLE
Getting error: undefined method `[]' for nil:NilClass with newest pre version

### ISSUE THREAD

**Issue by jrisch** [ttscoff/doing#75]
I've tested it with the following Ruby versions:
- 1.9.3-p551
- 2.0.0p645
- 2.1.6
- 2.2.3

All with a clean install by running `gem install --pre doing`

I'm typing `doing now test` and get `error: undefined method '[]' for nil:NilClass` back.

I'm using rbenv to switch between the ruby versions and I'm on MacOS 10.11

**Comment by vcavallo** [comment]
Hello @jrisch.
[this](https://github.com/ttscoff/doing/issues/58) should help you. it was the solution for me and for others.

namely, it is adding this to the top of your config file:

```
autotag:
    whitelist: []
    synonyms: {}
```

**Comment by jrisch** [comment]
Thank you - that indeed fixed the error.

**Comment by vcavallo** [comment]
Proposed fix: https://github.com/ttscoff/doing/pull/76

**Comment by jeff1618** [comment]
Thanks vcavallo. That fixed the same problem for me as well.

**Comment by vcavallo** [comment]
Awesome! Glad to hear it @jeff1618 !

**Comment by mediapathic** [comment]
Dropping another thanks for @vcavallo , I was having the same issue, so, thank you!
