### ISSUE TITLE
'doing open' fails with vim

### ISSUE THREAD

**Issue by claman** [ttscoff/doing#82]
`LSOpenURLsWithRole() failed for the application /usr/bin/vim with error -10810 for the file /Users/alexclaman/Dropbox/Apps/what_was_i_doing.md.`

**Comment by ttscoff** [comment]
It's trying to use the OS X open command, which won't work with vim (it 
will with MacVim, et al). You need to use the -e switch to execute vim 
directly.

**Comment by claman** [comment]
Thanks
