### ISSUE TITLE
Use tab character instead of spaces in the "doing" file

### ISSUE THREAD

**Issue by fnurl** [ttscoff/doing#85]
The new Taskpaper 3 preview does not like the use of spaces for indentation. Seems like TaskPaper changed file format to tabs for indentation rather than tabs or spaces a while ago.
- old: http://imissmymac.com/wp-content/uploads/2013/02/TaskPaper-Users-Guide.pdf
- new: http://blog.hogbaysoftware.com/post/396651972/taskpaper-iphone-file-format-changes

Would it be possible to change the indentation to a tab rather than 4 spaces?

**Comment by vcavallo** [comment]
I was _just_ 20 minutes ago lamenting TaskPaper's insistence on tabs... Personally, I dislike the idea of inserting tabs in the doing file, but I'm just one user ¯\_(ツ)_/¯

**Comment by fnurl** [comment]
I'm usually more of a space person myself, but it seemed easier to fix it in doing rather than in Taskpaper. I guess I can always make an alias and have sed fix the doing file afterwards... (I wasn't proficient enough in Ruby to find and patch a local copy of doing..

**Comment by vcavallo** [comment]
@fnurl I could help you locate your local `doing` gem if want to patch the version on your system. Alternatively, you could fork the gem, make your change there and run your own version..

**Comment by ttscoff** [comment]
I do plan to look into fixing this soon. The tab requirement in TaskPaper came when the iOS version was released for parsing reasons. I'll try to update soon.


Thanks,

Brett

**Comment by frandsoh** [comment]
@ttscoff - Thanks, Brett, for making doing (and all your other cool stuff)! I was wondering if you ever got around taking a look at the 'tab vs space' thingy?
I believe this is why the notes aren't indented correctly, am I right?

@vcavallo - Did you ever find a way to change this?

Thanks, Brett, for making doing (and all the other cool stuff)!
Frands

**Comment by ttscoff** [comment]
@frandsoh Sorry, I let this one slip. Will try to get back to it soon.

**Comment by amirahmajid** [comment]
I love, love, love Doing and am so grateful to have it. I use it with Taskpaper as well and I tried to figure out a fix for the tab issue but I am not a programmer. When I add a note not only does it not indent, it un-indents all previous note entries. I manually fixed them in Taskpaper but they just un-indent the next time Doing adds an entry. So none of my notes are connected to their titles anymore. 
Weirdly too any entries added directly in Taskpaper get shifted above the project name after a Doing entry is made. Any help is very appreciated.

**Comment by ttscoff** [comment]
I just pushed version 1.0.42, which fixes note indentation. Or it 
should. Let me know how it works for you.

As far as adding entries in TaskPaper, doing isn't really designed for 
manual editing. Each entry has to follow a specific pattern, with the 
date in ISO format, a pipe (|), and then the entry. If any entry doesn't 
conform to that format, it's not cataloged, and when doing writes the 
file back out it won't be part of any section. You can use TaskPaper to 
manually adjust times, toggle @done tags, etc, but adding new entries 
can be tricky.

The idea is that the "What was I doing" file is a separate file from any 
actual project management taskpaper files. If you need to add one-off 
items to it, you should do it using doing. If you do try it manually, 
make sure to match the formatting of all the other entries.

-Brett

**Comment by amirahmajid** [comment]
I forgot to post back to you that YES it totally works and I am very, very grateful to you for making this work. I really appreciate it and thank you also for your patient explanation of what is/was going on and why.
