### ISSUE TITLE
~/.doingrc is overwritten on every doing execution

### ISSUE THREAD

**Issue by dmitrym0** [ttscoff/doing#89]
~/.doingrc seems to be overwritten on every `doing` execution. Is this an intended behavior? I added a custom view to it but it was removed on overwite.

**Comment by ttscoff** [comment]
doing reads in the rc file and rewrites it after execution (with 
additional info). If your view is properly formatted, it should remain 
in the data written back out. If this isn't the case, please attach a 
copy of the doingrc file so I can test.

Thanks,
Brett
