### ISSUE TITLE
& character in title causes issues.

### ISSUE THREAD

**Issue by StyxOfDynamite** [ttscoff/doing#92]
Just added a note

`doing now work on Q&A widget`

Not sure if it's something you are able to address or if I'll just have to quote `"` my title's in future?

**Comment by vcavallo** [comment]
Hi. Which version of the gem are you using?

**Comment by ttscoff** [comment]
Because you're using it from the command line and the ampersand is always a special character in most shells, it's a good idea to quote any string containing special characters.

doing now "working on Q&A widget"

- Brett

**Comment by StyxOfDynamite** [comment]
Thought as much. I'll remember to quote strings in future. Cheers.
